version: 2
jobs:
  test_classification_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv ml_deployment_env
            . ml_deployment_env/bin/activate
            pip install --upgrade pip
            pip install -r packages/classification_model/requirements.txt
            chmod +x ./scripts/fetch_kaggle_dataset.sh
            ./scripts/fetch_kaggle_dataset.sh
            py.test -vv packages/classification_model/tests

train_and_upload_classification_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run: 
          name: Setup env
          command: |
            virtualenv ml_deployment_env
            . ml_deployment_env/bin/activate
            pip install -r packages/classification_model/requirements.txt
      - run: 
          name: Publish model
          command: |
            . ml_deployment_env/bin/activate
            chmod +x ./scripts/fetch_kaggle_dataset.sh ./scripts/publish_model.sh
            ./scripts/fetch_kaggle_dataset.sh
            PYTHONPATH=./packages/classification_model python3 packages/classification_model/classification_model/train_pipeline.py
            ./scripts/publish_model.sh ./packages/classification_model/

            
workflows:
  version: 2
  test-all:
    jobs:
      - test_classification_model
      - train_and_upload_classification_model 
